const express = require("express")
const { connection } = require("./Config/db.js")
const { UserModel } = require("./Models/User")
const cors = require('cors');

const app = express()

require("dotenv").config()
app.use(express.json())
app.use(cors());

app.get("/", (req, res) => {
    res.send("welcome")
})


let str = `LLLLLLLWLWLLLWLLLLLLLLWWLLLLWWWLLWLLLLLLLLLLLLWLLLLLLLLLLWLLLLLLLLLWLLWLWLWLLLLLLLLLWLLLLLLWLLWLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLWLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLWLLWLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLWLLWLLLLLLLLWLLLLLLLWLLLLLLLLLLLLLLLWWLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLWLLLLWWLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLWWLLWWLLLLWLLWWWLLLWLWLLLLLLLLWLLLLLLLLWLLLLWLLLWWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLLLWLLLLLLWWLLWLLLLLLLLLLLLLLLLLLLWLLLLLWLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLWLLLLLLLLLLLLLLLLLLLLWLLLLWLLLLWLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLWWLLLWLLLLLLWLLWLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLWWLLLWLLLLLWLLLLWLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLWWLLLLLLWLLLLLLLLLLLLLLLLLWLLLLLLLLWLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLWLLWLLLLLLLLLLLLLWLLLLLLLLLLLLWLLLWLLLLWLLLLLLLLLLLLWLLLLLWLLWLLLLWLLLLLWLLLLLLLLLLLLLLLLLWWLLLLLLLLLLLLLLWLLLLLLLLLWLLWLLLLLLLLLLLLLLLLLLLLLLLWLLLWLLLLLLLLLLLLLLLWWLLLLLLLLWLLLLLLLWWLLLLLWLLWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLWWLLLLLLLLLWLLLLLLLLLLLLLWLLLLLLLLLLLLLWWLLWLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLWLLWLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLWLLWLLLLWLLLLLLLLLLLLLLLLLWWLLLLLLLLLWLLLLLLWLLWLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLWLLLLLWLLLLLLLWLLLLLLLLLLWLLLLLLLLLLWLLLLLLLLLWLLLLLLLLLWLWLLLLLLLLLLLLLLLLLLLLWWLWLLLLLLLLLLLLLWLLLWLLLWLLLLLWLLLLLLLLLLLWWLLLLLLLLLLLLLLLLWLLLLLLLLLWLLWLWLLLLLWLLLLLLLLLLWLLLLLLLWLLWWLLLLLWLLLLWLLWLLLLLLLLLLLLLLWLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLWLWLLLWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLWLLWLLLLLLLWWLLLLLLLLLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLWLLLLLLLLLWLLLLLWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLWLWLLWLLWLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLWLLLLLLLLLLWLWLLWLLWLLLLLLLWWWLWLLLLWLLLLLWLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLWLLLLLWLLLLLLLLLLLWLLLLLLLLWLLLWLLLLLLLWLLLLLLLLLLLLLLLWLLLLLLLWLLWLLWLWLLLWLLLLLLLLLLWLLLLLLWLLLLLLLWLLLLLLLLLLWWLLLLLLLLLLLLWLLLLLLLLLLLLLLLLWLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLWLLLLLLLLLWLLLLLLLLWLLWWWLLLLLLLLLLLLWLLWLLLLLLLWLLLLLWLLLLWLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLWLLLLWLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLWLLWLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLLLWLLLLLLLLWLLLLLLLLLLLLLLLLLWLLLLLLWLLLLWLLLLLWLLLLLLWLLWWLLLWLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLWLWWLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLWWLLLLLLLWLWLLWLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLWLLLLWLLLWWLLLLLLLLWLLLLLLWWLLLLLLLLLLLLLLLLLLLWLWLLLLLLLLLLLLLLLLLLLLLLLLLWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLWLLWLLLLLLLLLLLLLLLWLLLLLWLLWWLLLLLWLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLWLLLLLWLLWWWWLLLLWLWLLWWWWWLLWWLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLWLLLLLLLLLLWWLLLWLLWLLLLLLLWLLLLLLLLLLLLLLLLLWWLLLLWLLLWLLLWLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLWLWLLLLLLLLLLLLLLLLLLLLLWWLLLLLLLLLLWLLLLLLLLLLLLLWLLLWLLLLLLLLLLWLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLWLLLLLLWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLWLLLLWLWLLWLLLLWLLLLLWLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLWLLLLLLLLLLWLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLWLLWLLLLLLLLLLLLLLLLLLLLLLWLLWLLLLLLLLLLLWLLWLLLLLLLLWLLWLLLLLLWLLLLLLLLLLLLLLWWWLLLLLLLLLLLLLLLLLWLLLLLLLWLLLLLWLLLLLLLLLLLLLLLLLLLLWLLLLWLLLLLLLLLLLLWLLLLWLLLLLLLLLLLLLLWLLLWLLLLWLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLWLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLWLLLLLLWLLWLLLLWLLLLWLLLLLLLLLLLWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLWLLLLLLLLLLWWLLLLLLLLWLWLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLWWLLWLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLWLLLLLLWLLLWLLLLWLLLLLLLLLWLWLLLLLLLLWLLLLLWLLLLWLLLLLWLWLLWLLLLWLLWLLLLLLLLWLLLLLWLLWLLLLLLLLLLLLLLLLLLLLWLLLLLWLLLLWLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLWLLLLLLLLLLLWLLLLLLLLWWWLLLLWLLLLWLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLWLLLLLWLWLWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLWLWLLLWWLLLLLLLLLLLLLWLLLLWLLLLWLLWLLLLLLLLLLWLLLLLLLLLLLLLLLLLLWLLLLWLLLLWLLLLLLWLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLWLLLLLWLWLLLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLWLLLLLLLLLLLLLWLLLLLLWLLLLLWLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLWLLLLLWLLLWLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLLLLLLLLLLLWLWWLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLLLLLLLWLLLLLLLLLWLLLLLLLWLLLLLLLLLLLLWLLLLLLLLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWLLLLLLLWWLLWLLLLLLLLLLLLLLLLWLLLLLLWLLLLLLWLLLLLLLLLLWLLWLLLLLLLLLLLLLWLWLLLLWLLLLLWLLLLLWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL`


app.post("/signup", async (req, res) => {
    console.log(req.body)
    let { firstname,
        middlename,
        lastname,
        mobileno } = req.body
    console.log(firstname,
        middlename,
        lastname,
        mobileno)

    try {

        let result = await UserModel.countDocuments();
        if (result > 0) {
            const user = new UserModel({
                firstname,
                middlename,
                lastname,
                mobileno,
                result: str[result]
            });
            await user.save();
            res.send({ src: str[result], result })

        } else {
            res.status(500).send("Something went wrong or invalid or used credentials. Please try again later.");
        }


        // res.send("Internal error")
        // Save the user to the database

        console.log(result)
        console.log(str[result - 1])
        //await user.save();

    } catch (err) {
        console.error(err);
        res.status(500).send("Something went wrong or invalid or used credentials. Please try again later.");
    }
});



app.get("/dashboard", async (req, res) => {
    // console.log(req.query)
    try {
        // Hash the password
        let ressultdata = await UserModel.find({})
        res.send(ressultdata)
    } catch (err) {///
        ////
        res.status(500).send("Error retrieving data from API.");
    }////


});


app.listen(7500, async () => {
    try {
        await connection
        console.log("connected")
    }
    catch (err) {
        console.log("not connected")
        console.log(err)
    }
    console.log("linstening to port 7500")
    // console.log(process.env.NAME)
    //console.log(process.env.MONGO_URL)
})